### PR TITLE
Use expr.parse to fix issue with bracket expression with :to

### LINKED ISSUE #496: Cannot use a Bracket Expression with :to bindings
This works:

```
        <fr-om val:from="obj['from']"></fr-om>
```

...but this:
```
        <t-o val:to="obj['to']"></t-o>
```

Tries to set the literal `"obj['to']"` on the ViewModel instead of parsing the expression.

Here is a codepen: https://codepen.io/kphillips86/pen/pxpBEL?editors=0011.

This should use `expression.parse`:

https://github.com/canjs/can-stache-bindings/blob/d3d342c8dbc0e548480d79a5ba9f8f36bc10b0cf/can-stache-bindings.js#L591-L593

like the other path does:

https://github.com/canjs/can-stache-bindings/blob/d3d342c8dbc0e548480d79a5ba9f8f36bc10b0cf/can-stache-bindings.js#L579-L582

### PR DESCRIPTION
**Pull request by Mattchewone**
This fixes https://github.com/canjs/can-stache-bindings/issues/496 allowing bracket notation with `:to`

### CODE REVIEW

File: test/colon/element-test.js [hunk 1]
```diff
@@ -1287,4 +1287,32 @@ testHelpers.makeTests("can-stache-bindings - colon - element", function(name, do
...
+	testIfRealDocument("Bracket Expression with :to bindings", function () {
+		var demoContext = new DefineMap({
+			person: {
+				name: 'Matt'
+			}
+		});
+
+		var SourceComponentVM = DefineMap.extend("SourceComponentVM", {
+			name: {
+				value: 'Kevin'
```
Comment (phillipskevin) [inline test/colon/element-test.js]: Can you use `default` instead of `value`?

**Review by phillipskevin — CHANGES_REQUESTED** [review]
One small thing, but otherwise looks good.

File: test/colon/element-test.js (hunk 1 above)
Comment (Mattchewone) [reply test/colon/element-test.js]: Sure was just trying to be consistent with what i'd seen in other tests. np.

**Review by phillipskevin — APPROVED** [review]
